# Generated by Django 3.2.13 on 2022-05-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_diameter', models.IntegerField()),
            ],
            options={
                'ordering': ['material', 'internal_diameter'],
            },
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equivalent_length', models.IntegerField()),
            ],
            options={
                'ordering': ['diameter', 'name', 'equivalent_length'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hazen_williams_coefficient', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equivalent_length', models.IntegerField()),
                ('inlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_reductions', to='shp.diameter')),
                ('outlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_reductions', to='shp.diameter')),
            ],
            options={
                'ordering': ['inlet_diameter', 'outlet_diameter', 'name', 'equivalent_length'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equivalent_length', models.IntegerField()),
                ('inlet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_material_connections', to='shp.material')),
                ('outlet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_material_connections', to='shp.material')),
            ],
            options={
                'ordering': ['inlet_material', 'outlet_material', 'name', 'equivalent_length'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='shp_materia_name_c48633_idx'),
        ),
        migrations.AddField(
            model_name='fitting',
            name='diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='shp.diameter'),
        ),
        migrations.AddField(
            model_name='diameter',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diameters', to='shp.material'),
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['inlet_diameter', 'outlet_diameter'], name='shp_reducti_inlet_d_a83949_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reduction',
            unique_together={('inlet_diameter', 'outlet_diameter')},
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['inlet_material', 'outlet_material'], name='shp_materia_inlet_m_f54b1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialconnection',
            unique_together={('inlet_material', 'outlet_material')},
        ),
        migrations.AddIndex(
            model_name='fitting',
            index=models.Index(fields=['diameter'], name='shp_fitting_diamete_84eac6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fitting',
            unique_together={('diameter', 'name')},
        ),
        migrations.AddIndex(
            model_name='diameter',
            index=models.Index(fields=['material'], name='shp_diamete_materia_0b404f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diameter',
            unique_together={('material', 'name')},
        ),
    ]
