# Generated by Django 3.2.13 on 2022-06-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('internal_diameter', models.IntegerField(verbose_name='diâmetro interno')),
            ],
            options={
                'verbose_name': 'diâmetro',
                'verbose_name_plural': 'diâmetros',
                'ordering': ['material', 'internal_diameter'],
            },
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'conexão',
                'verbose_name_plural': 'conexões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('hazen_williams_coefficient', models.IntegerField(verbose_name='coeficiente de hazen-williams')),
                ('default_diameter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_diameter_materials', to='shp.diameter', verbose_name='Diâmetro padrão')),
                ('one_outlet_connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_outlet_materials', to='shp.fitting', verbose_name='conexão para uma saída')),
                ('three_outlet_connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_outlet_materials', to='shp.fitting', verbose_name='conexão para três saídas')),
                ('two_outlet_connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_outlet_materials', to='shp.fitting', verbose_name='conexão para duas saídas')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('equivalent_length', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='comprimento equivalente')),
                ('inlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_reductions', to='shp.diameter', verbose_name='diâmetro de Entrada')),
                ('outlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_reductions', to='shp.diameter', verbose_name='diâmetro de Saída')),
            ],
            options={
                'verbose_name': 'redução',
                'verbose_name_plural': 'reduções',
                'ordering': ['name', 'equivalent_length'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('equivalent_length', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Comprimento equivalente')),
                ('inlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_diameter_connections', to='shp.diameter', verbose_name='diâmetro do material de Entrada')),
                ('inlet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_material_connections', to='shp.material', verbose_name='Material de Entrada')),
                ('outlet_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_diameter_connections', to='shp.diameter', verbose_name='diâmetro do material de Saída')),
                ('outlet_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_material_connections', to='shp.material', verbose_name='Material de Saída')),
            ],
            options={
                'verbose_name': 'conexão entre materiais',
                'verbose_name_plural': 'conexões entre materiais',
                'ordering': ['name', 'equivalent_length'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('nozzle_type', models.CharField(choices=[('TC', 'tronco-cônico'), ('RE', 'regulável'), ('MA', 'mangotinho')], max_length=2, verbose_name='tipo do hidrante')),
                ('reductions_ids', models.JSONField(default=list, verbose_name='reduções')),
                ('fittings_ids', models.JSONField(default=list, verbose_name='conexões')),
                ('extra_equivalent_length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='comprimento equivalente extra')),
                ('hose_hazen_williams_coefficient', models.IntegerField(verbose_name='coeficiente de hazen-williams da mangueira')),
                ('hose_internal_diameter', models.IntegerField(verbose_name='diâmetro interno da mangueira')),
                ('k_factor', models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='coeficiente de vazão do esguicho')),
                ('k_factor_includes_hose', models.BooleanField(default=False, verbose_name='coeficiente de vazão inclue a mangueira')),
                ('k_nozzle', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='coeficiente próprio do esguicho')),
                ('outlet_diameter', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='diâmetro da saída')),
                ('minimum_flow_rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='vazão mínima no esguicho')),
                ('inlet_diameter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='shp.diameter', verbose_name='diâmetro de Entrada')),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='shp.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'hidrante',
                'verbose_name_plural': 'hidrantes',
                'ordering': ['name', 'inlet_diameter', 'outlet_diameter'],
            },
        ),
        migrations.CreateModel(
            name='FittingDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalent_length', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='comprimento equivalente')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_lengths', to='shp.diameter', verbose_name='diâmetro')),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_lengths', to='shp.fitting', verbose_name='conexão')),
            ],
            options={
                'verbose_name': 'conexão-diâmetro',
                'verbose_name_plural': 'conexões-diâmetros',
                'ordering': ['fitting', 'diameter', 'equivalent_length'],
            },
        ),
        migrations.AddField(
            model_name='diameter',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diameters', to='shp.material', verbose_name='material'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_type', models.CharField(choices=[('VM', 'Vazão mínima'), ('VR', 'Vazão Residual')], default='VM', max_length=2, verbose_name='tipo de cálculo')),
                ('pressure_type', models.CharField(choices=[('GR', 'Gravitacional'), ('BO', 'Bomba')], default='GR', max_length=2, verbose_name='tipo de pressurização')),
                ('fixture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shp.fixture', verbose_name='Hidrante padrão')),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shp.material', verbose_name='Material padrão')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['inlet_diameter'], name='shp_reducti_inlet_d_edfd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['outlet_diameter'], name='shp_reducti_outlet__c57e26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reduction',
            unique_together={('inlet_diameter', 'outlet_diameter')},
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['inlet_material'], name='shp_materia_inlet_m_80b4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['inlet_diameter'], name='shp_materia_inlet_d_7ac312_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['outlet_material'], name='shp_materia_outlet__c51983_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['outlet_diameter'], name='shp_materia_outlet__debd39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialconnection',
            unique_together={('inlet_material', 'inlet_diameter', 'outlet_material', 'outlet_diameter')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='shp_materia_name_c48633_idx'),
        ),
        migrations.AddIndex(
            model_name='fittingdiameter',
            index=models.Index(fields=['fitting'], name='shp_fitting_fitting_25a77a_idx'),
        ),
        migrations.AddIndex(
            model_name='fittingdiameter',
            index=models.Index(fields=['diameter'], name='shp_fitting_diamete_c5fdb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fittingdiameter',
            unique_together={('fitting', 'diameter')},
        ),
        migrations.AddIndex(
            model_name='diameter',
            index=models.Index(fields=['material'], name='shp_diamete_materia_0b404f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diameter',
            unique_together={('material', 'name')},
        ),
    ]
