# Generated by Django 3.2.13 on 2022-05-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diameter',
            options={'ordering': ['material', 'internal_diameter'], 'verbose_name': 'diâmetro'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'material'},
        ),
        migrations.AlterField(
            model_name='diameter',
            name='internal_diameter',
            field=models.IntegerField(verbose_name='diâmetro interno'),
        ),
        migrations.AlterField(
            model_name='diameter',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diameters', to='shp.material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='diameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='shp.diameter', verbose_name='Diâmetro'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='equivalent_length',
            field=models.IntegerField(verbose_name='Comprimento equivalente'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='material',
            name='hazen_williams_coefficient',
            field=models.IntegerField(verbose_name='coeficiente de hazen-williams'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='materialconnection',
            name='equivalent_length',
            field=models.IntegerField(verbose_name='Comprimento equivalente'),
        ),
        migrations.AlterField(
            model_name='materialconnection',
            name='inlet_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_material_connections', to='shp.material', verbose_name='Material de Entrada'),
        ),
        migrations.AlterField(
            model_name='materialconnection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='materialconnection',
            name='outlet_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_material_connections', to='shp.material', verbose_name='Material de Saída'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='equivalent_length',
            field=models.IntegerField(verbose_name='Comprimento equivalente'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='inlet_diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlet_reductions', to='shp.diameter', verbose_name='Diâmetro de Entrada'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='outlet_diameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_reductions', to='shp.diameter', verbose_name='Diâmetro de Saída'),
        ),
    ]
