# Generated by Django 3.2.13 on 2022-05-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_auto_20220527_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitting',
            options={'ordering': ['material', 'name']},
        ),
        migrations.AddField(
            model_name='fitting',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='shp.material', verbose_name='material'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fitting',
            unique_together={('material', 'name')},
        ),
        migrations.AddIndex(
            model_name='fitting',
            index=models.Index(fields=['material'], name='shp_fitting_materia_a1d092_idx'),
        ),
    ]
