# Generated by Django 3.2.13 on 2022-05-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0005_auto_20220528_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fittingdiameter',
            options={'ordering': ['material', 'fitting', 'diameter', 'equivalent_length']},
        ),
        migrations.AlterModelOptions(
            name='reduction',
            options={'ordering': ['material', 'inlet_diameter', 'outlet_diameter', 'name', 'equivalent_length']},
        ),
        migrations.RemoveIndex(
            model_name='materialconnection',
            name='shp_materia_inlet_m_f54b1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='reduction',
            name='shp_reducti_inlet_d_a83949_idx',
        ),
        migrations.AddField(
            model_name='fittingdiameter',
            name='material',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='fittingdiameters', to='shp.material', verbose_name='material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reduction',
            name='material',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='shp.material', verbose_name='material'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fittingdiameter',
            unique_together={('material', 'fitting', 'diameter')},
        ),
        migrations.AlterUniqueTogether(
            name='reduction',
            unique_together={('material', 'inlet_diameter', 'outlet_diameter')},
        ),
        migrations.AddIndex(
            model_name='fittingdiameter',
            index=models.Index(fields=['material'], name='shp_fitting_materia_6595d9_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['inlet_material'], name='shp_materia_inlet_m_80b4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconnection',
            index=models.Index(fields=['outlet_material'], name='shp_materia_outlet__c51983_idx'),
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['material'], name='shp_reducti_materia_60fb60_idx'),
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['inlet_diameter'], name='shp_reducti_inlet_d_edfd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='reduction',
            index=models.Index(fields=['outlet_diameter'], name='shp_reducti_outlet__c57e26_idx'),
        ),
    ]
