# Generated by Django 3.2.13 on 2022-05-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0006_auto_20220529_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='one_outlet_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_outlet_materials', to='shp.fitting', verbose_name='Conexão para uma Saída'),
        ),
        migrations.AddField(
            model_name='material',
            name='three_outlet_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_outlet_materials', to='shp.fitting', verbose_name='Conexão para três Saídas'),
        ),
        migrations.AddField(
            model_name='material',
            name='two_outlet_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_outlet_materials', to='shp.fitting', verbose_name='Conexão para duas Saídas'),
        ),
    ]
