# Generated by Django 3.2.13 on 2022-05-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0007_auto_20220530_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fittingdiameter',
            options={'ordering': ['fitting', 'diameter', 'equivalent_length']},
        ),
        migrations.AlterModelOptions(
            name='reduction',
            options={'ordering': ['inlet_diameter', 'outlet_diameter', 'name', 'equivalent_length']},
        ),
        migrations.RemoveIndex(
            model_name='fittingdiameter',
            name='shp_fitting_materia_6595d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='reduction',
            name='shp_reducti_materia_60fb60_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fittingdiameter',
            unique_together={('fitting', 'diameter')},
        ),
        migrations.AlterUniqueTogether(
            name='reduction',
            unique_together={('inlet_diameter', 'outlet_diameter')},
        ),
        migrations.RemoveField(
            model_name='fittingdiameter',
            name='material',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='material',
        ),
    ]
