# Generated by Django 3.2.13 on 2022-05-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0008_auto_20220530_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='one_outlet_connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_outlet_materials', to='shp.fitting', verbose_name='Conexão para uma Saída'),
        ),
        migrations.AlterField(
            model_name='material',
            name='three_outlet_connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_outlet_materials', to='shp.fitting', verbose_name='Conexão para três Saídas'),
        ),
        migrations.AlterField(
            model_name='material',
            name='two_outlet_connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_outlet_materials', to='shp.fitting', verbose_name='Conexão para duas Saídas'),
        ),
    ]
