# Generated by Django 3.2.13 on 2022-05-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0010_auto_20220530_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixtures',
            new_name='Fixture',
        ),
    ]
