# Generated by Django 3.2.13 on 2022-05-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0012_auto_20220531_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fittings',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='fixtures', to='shp.Fitting', verbose_name='conexões'),
        ),
    ]
