# Generated by Django 3.2.13 on 2022-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0014_auto_20220602_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitting',
            options={'ordering': ['name'], 'verbose_name': 'conexão', 'verbose_name_plural': 'conexões'},
        ),
        migrations.RemoveIndex(
            model_name='fitting',
            name='shp_fitting_materia_a1d092_idx',
        ),
        migrations.AlterField(
            model_name='fitting',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='fittings',
            field=models.ManyToManyField(blank=True, default=None, related_name='fixtures', to='shp.Fitting', verbose_name='conexões'),
        ),
        migrations.AlterUniqueTogether(
            name='fitting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fitting',
            name='material',
        ),
    ]
