# Generated by Django 3.2.13 on 2022-06-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0015_auto_20220608_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialconnection',
            options={'ordering': ['inlet_diameter', 'outlet_diameter', 'name', 'equivalent_length'], 'verbose_name': 'conexão entre materiais', 'verbose_name_plural': 'conexões entre materiais'},
        ),
        migrations.RemoveIndex(
            model_name='materialconnection',
            name='shp_materia_inlet_m_80b4a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialconnection',
            name='shp_materia_outlet__c51983_idx',
        ),
        migrations.AddField(
            model_name='fixture',
            name='hose_internal_diameter',
            field=models.IntegerField(default=40, verbose_name='diâmetro interno da mangueira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='reductions',
            field=models.ManyToManyField(blank=True, default=None, related_name='fixtures', to='shp.Reduction', verbose_name='reduções'),
        ),
        migrations.AddField(
            model_name='material',
            name='default_diameter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_diameter_materials', to='shp.diameter', verbose_name='Diâmetro padrão'),
        ),
        migrations.AlterUniqueTogether(
            name='materialconnection',
            unique_together={('inlet_diameter', 'outlet_diameter')},
        ),
        migrations.RemoveField(
            model_name='materialconnection',
            name='inlet_material',
        ),
        migrations.RemoveField(
            model_name='materialconnection',
            name='outlet_material',
        ),
    ]
