# Generated by Django 3.2.13 on 2022-06-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0016_auto_20220608_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialconnection',
            options={'ordering': ['name', 'equivalent_length'],
                     'verbose_name': 'conexão entre materiais', 'verbose_name_plural': 'conexões entre materiais'},),
        migrations.AlterModelOptions(
            name='reduction',
            options={'ordering': ['name', 'equivalent_length'],
                     'verbose_name': 'redução', 'verbose_name_plural': 'reduções'},),
        migrations.AddField(
            model_name='materialconnection', name='inlet_material', field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, related_name='inlet_material_connections',
                to='shp.material', verbose_name='Material de Entrada'),
            preserve_default=False,),
        migrations.AddField(
            model_name='materialconnection', name='outlet_material', field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_material_connections',
                to='shp.material', verbose_name='Material de Saída'),
            preserve_default=False,),
        migrations.AlterField(
            model_name='materialconnection', name='inlet_diameter', field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='inlet_diameter_connections',
                to='shp.diameter', verbose_name='diâmetro do material de Entrada'),),
        migrations.AlterField(
            model_name='materialconnection', name='outlet_diameter', field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='outlet_diameter_connections',
                to='shp.diameter', verbose_name='diâmetro do material de Saída'),),
        migrations.AlterUniqueTogether(
            name='materialconnection',
            unique_together={('inlet_material', 'inlet_diameter', 'outlet_material', 'outlet_diameter')},),
        migrations.AddIndex(
            model_name='materialconnection', index=models.Index(
                fields=['inlet_material'],
                name='shp_materia_inlet_m_80b4a2_idx'),),
        migrations.AddIndex(
            model_name='materialconnection', index=models.Index(
                fields=['outlet_material'],
                name='shp_materia_outlet__c51983_idx'),), ]
