# Generated by Django 3.2.13 on 2022-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0017_auto_20220612_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='k_factor_includes_hose',
            field=models.BooleanField(default=False, verbose_name='coeficiente de vazão inclue a mangueira'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='k_nozzle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='coeficiente próprio do esguicho'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='k_factor',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='coeficiente de vazão do esguicho'),
        ),
    ]
