# Generated by Django 3.2.13 on 2022-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0018_auto_20220614_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='type',
            new_name='nozzle_type',
        ),
    ]
