# Generated by Django 3.2.13 on 2022-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0019_rename_type_fixture_nozzle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='fittings',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='reductions',
        ),
        migrations.AddField(
            model_name='fixture',
            name='fittings_ids',
            field=models.JSONField(default=list, verbose_name='conexões'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='reductions_ids',
            field=models.JSONField(default=list, verbose_name='reduções'),
        ),
    ]
