# Generated by Django 3.2.13 on 2022-06-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0020_auto_20220616_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_type', models.CharField(choices=[('VM', 'Vazão mínima'), ('VR', 'Vazão Residual')], default='VM', max_length=2, verbose_name='tipo de cálculo')),
                ('pressure_type', models.CharField(choices=[('GR', 'Gravitacional'), ('BO', 'Bomba')], default='GR', max_length=2, verbose_name='tipo de pressurização')),
                ('fixture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shp.fixture', verbose_name='Hidrante padrão')),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shp.material', verbose_name='Material padrão')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
    ]
