# Generated by Django 3.2.13 on 2023-10-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0002_auto_20230801_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas',
            name='start_pressure',
        ),
    ]
