# Generated by Django 3.2.13 on 2023-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0004_auto_20231009_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['name'], 'verbose_name': 'gas', 'verbose_name_plural': 'gases'},
        ),
        migrations.AddField(
            model_name='gas',
            name='pck',
            field=models.IntegerField(default=10, verbose_name='poder calorifico (kcal/Kg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gas',
            name='pci',
            field=models.IntegerField(verbose_name='poder calorifico inferior (kcal/m³)'),
        ),
    ]
