# Generated by Django 3.2.13 on 2023-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('document', models.CharField(max_length=255, verbose_name='documento')),
            ],
            options={
                'verbose_name': 'signatário',
                'verbose_name_plural': 'signatários',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='signatory',
            index=models.Index(fields=['name'], name='core_signat_name_c4fc94_idx'),
        ),
    ]
